In [1]:
import numpy as np

# Scalars

In [12]:
c = np.array(12)

In [13]:
c

array(12)

In [14]:
c.ndim

0

# Vectors

In [5]:
x = np.array([12, 3, 6, 14, 7])

In [15]:
x

array([12,  3,  6, 14,  7])

In [16]:
x.ndim

1

# Matrices

In [19]:
M = np.array([
    [5, 78, 2, 34, 0],
    [6, 79, 3, 25, 1],
    [7, 80, 4, 36, 2],
])

In [20]:
M

array([[ 5, 78,  2, 34,  0],
       [ 6, 79,  3, 25,  1],
       [ 7, 80,  4, 36,  2]])

In [18]:
M.ndim

2

# 3D Tensor

In [21]:
T = np.array([
    [
        [5, 78, 2, 34, 0],
        [6, 79, 3, 25, 1],
        [7, 80, 4, 36, 2],
    ],
    [
        [5, 78, 2, 34, 0],
        [6, 79, 3, 25, 1],
        [7, 80, 4, 36, 2],
    ],
    [
        [5, 78, 2, 34, 0],
        [6, 79, 3, 25, 1],
        [7, 80, 4, 36, 2],
    ],
])

In [23]:
T.ndim

3

# Tensor Manipulations

In [33]:
import keras

(train_images, train_labels), (test_images, test_labels) = keras.datasets.mnist.load_data()

In [34]:
train_images[10:100].shape

(90, 28, 28)

In [36]:
np.array_equal(train_images[10:100], train_images[10:100, :, :])

True

In [37]:
np.array_equal(train_images[10:100, :, :], train_images[10:100, 0:28, 0:28])

True

In [39]:
bottom_right_corner = train_images[:, 14:, 14:]

In [38]:
center_of_image = train_images[:, 7:-7, 7:-7]

# Tensor Operations

## Element-wise Operations

In [ ]:
def naive_relu(x):
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] = max(x[i, j], 0)
    return x

# i.e.
np.maximum(np.array([1,2,3]), 0)

In [ ]:
def naive_add(x, y):
    assert np.array_equal(x.shape, y.shape)

    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] += y[i, j]
    return x

# i.e.
np.array([1,2,3]) + np.array([4,5,6])

## Broadcasting

Changing the shape of a smaller tensor to match that of a larger tensor.
- Axes (called *broadcast axes*) are added to the smaller tensor to match the `ndim` of the larger tensor.
- The smaller tensor is repeated alongside these new axes to match the full shape of the larger tensor.

In [ ]:
def naive_add_matrix_and_vector(x, y):
    assert len(x.shape) == 2
    assert len(y.shape) == 1
    assert x.shape[1] == y.shape[0]

    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] += y[j]

    return x

In [45]:
# i. e.
np.maximum(
    np.random.random((64, 3, 32, 10)),
    np.random.random((32, 10)),
).shape

(64, 3, 32, 10)

# Tensor Dot

In [ ]:
def naive_vector_dot(x, y):
    assert len(x.shape) == 1
    assert len(y.shape) == 1
    assert x.shape[0] == y.shape[0]
    
    z = 0
    for i in range(x.shape[0]):
        z += x[i] * y[i]
    return z

In [ ]:
def naive_matrix_vector_dot(X, y):
    assert len(X.shape) == 2
    assert len(y.shape) == 1
    assert X.shape[1] == y.shape[0]

    z = np.zeros(X.shape[0])
    for i in range(X.shape[0]):
        for j in range(X.shape[0]):
            z[i] += X[i, j] * y[j]

    return z

In [ ]:
def naive_matrix_dot(X, Y):
    assert len(X.shape) == 2
    assert len(Y.shape) == 2
    assert X.shape[1] == Y.shape[0]

    z = np.zeros((X.shape[0], Y.shape[1]))
    for i in range(X.shape[0]):
        for j in range(Y.shape[1]):
            row_x = X[i, :]
            column_y = Y[:, j]
            z[i, j] = naive_vector_dot[row_x, column_y]
    
    return z

# Tensor Reshaping

In [46]:
X = np.array([
    [0, 1,],
    [2, 3,],
    [4, 5,]
])

In [48]:
X.reshape((6, 1))

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [50]:
X.reshape((2, 3))

array([[0, 1, 2],
       [3, 4, 5]])

In [51]:
X.transpose()

array([[0, 2, 4],
       [1, 3, 5]])